sudo: false
language: python
matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35
    - python: "3.6"
      env: TOXENV=py36
install:
  - pip install -q 'setuptools>=36.0.1' 'pytest>=2.8.0' 'tox>=3.3.0'
  - python setup.py -q install
script: tox

